export const GET_PRODUCTIONS = 'GET_PRODUCTIONS';
export const GET_PRODUCTION = 'GET_PRODUCTION';
export const CREATE_PRODUCTION = 'CREATE_PRODUCTION';
export const UPDATE_PRODUCTION = 'UPDATE_PRODUCTION';
export const DELETE_PRODUCTION = 'DELETE_PRODUCTION';

export const GET_SEQUENCES = 'GET_SEQUENCES';
export const GET_SEQUENCE = 'GET_SEQUENCE';
export const CREATE_SEQUENCE = 'CREATE_SEQUENCE';
export const UPDATE_SEQUENCE = 'UPDATE_SEQUENCE';
export const DELETE_SEQUENCE = 'DELETE_SEQUENCE';

export const GET_SHOTS = 'GET_SHOTS';
export const GET_SHOT = 'GET_SHOT';
export const CREATE_SHOT = 'CREATE_SHOT';
export const UPDATE_SHOT = 'UPDATE_SHOT';
export const DELETE_SHOT = 'DELETE_SHOT';

export const GENERATE_SCRIPT = 'GENERATE_SCRIPT';
export const GENERATE_SCENE = 'GENERATE_SCENE';

