export const SET_PRODUCTIONS = 'SET_PRODUCTIONS';
export const SET_PRODUCTION = 'SET_PRODUCTION';
export const ADD_PRODUCTION = 'ADD_PRODUCTION';
export const UPDATE_PRODUCTION_STATE = 'UPDATE_PRODUCTION_STATE';
export const REMOVE_PRODUCTION = 'REMOVE_PRODUCTION';

export const SET_SEQUENCES = 'SET_SEQUENCES';
export const SET_SEQUENCE = 'SET_SEQUENCE';
export const ADD_SEQUENCE = 'ADD_SEQUENCE';
export const UPDATE_SEQUENCE_STATE = 'UPDATE_SEQUENCE_STATE';
export const REMOVE_SEQUENCE = 'REMOVE_SEQUENCE';

export const SET_SHOTS = 'SET_SHOTS';
export const SET_SHOT = 'SET_SHOT';
export const ADD_SHOT = 'ADD_SHOT';
export const UPDATE_SHOT_STATE = 'UPDATE_SHOT_STATE';
export const REMOVE_SHOT = 'REMOVE_SHOT';

export const SET_LOADING = 'SET_LOADING';
export const SET_ERROR = 'SET_ERROR';
export const SET_CURRENT_PRODUCTION = 'SET_CURRENT_PRODUCTION';
export const SET_CURRENT_SEQUENCE = 'SET_CURRENT_SEQUENCE';

